"""Generate phase for .NET Core: a deterministic GitHub Actions workflow.

The workflow is assembled from a fixed template plus the enabled steps from the
:class:`~ci_authoring.models.StepConfig`, so the same repo + config always yields
byte-identical YAML.

Steps use the PRD's Stage-1 substitution table (§8): **SonarQube** (substitute for
Fortify SAST), a **Trivy** filesystem scan for SCA (substitute for Sonatype), and,
per **FR-N.10**, a **container image** built and published to **GHCR** (the
substitute for Nexus) with a Trivy image scan (substitute for Wiz) and a CycloneDX
**SBOM**. A Dockerfile is generated when the repository has none. (.NET Framework
gets *no* image — FR-L.7.)

``build``/``test``/``sonar`` follow the required-steps config; ``scan`` and
``image`` are on by default and can be turned off per app via ``disabled_steps``
(PRD CR-2).
"""
from __future__ import annotations

from ci_authoring import Discovery, StepConfig, WorkflowArtifact, WorkflowGenerator

WORKFLOW_PATH = ".github/workflows/ci.yml"
DOCKERFILE_PATH = "Dockerfile"
#: Pinned to a real release tag — see github.com/aquasecurity/trivy-action/releases.
TRIVY_ACTION = "aquasecurity/trivy-action@0.35.0"

#: Map a target framework to (setup-dotnet version, docker base-image tag).
_SDK = {
    "net6.0": ("6.0.x", "6.0"),
    "net7.0": ("7.0.x", "7.0"),
    "net8.0": ("8.0.x", "8.0"),
}


def _sdk(target_framework: str | None) -> tuple[str, str]:
    return _SDK.get((target_framework or "").lower(), ("8.0.x", "8.0"))


def _main_project(discovery: Discovery) -> tuple[str | None, str]:
    """Best-effort main project ``(.csproj path, assembly name)`` — first non-test csproj."""
    for path in getattr(discovery, "project_files", []):
        lower = path.lower()
        if lower.endswith(".csproj") and "test" not in lower:
            return path, path.rsplit("/", 1)[-1][: -len(".csproj")]
    return None, "App"


def render_dockerfile(discovery: Discovery) -> str:
    """A best-effort .NET Core Dockerfile, generated only when the repo has none."""
    _, base_tag = _sdk(getattr(discovery, "target_framework", None))
    csproj, assembly = _main_project(discovery)
    publish = f'dotnet publish "{csproj}"' if csproj else "dotnet publish"
    return (
        "# Generated by the NetCoreCI agent. Review the base image (aspnet vs runtime)\n"
        "# and the ENTRYPOINT assembly name for your application before merging.\n"
        f"FROM mcr.microsoft.com/dotnet/sdk:{base_tag} AS build\n"
        "WORKDIR /src\n"
        "COPY . .\n"
        "RUN dotnet restore\n"
        f"RUN {publish} -c Release -o /app --no-restore\n"
        "\n"
        f"FROM mcr.microsoft.com/dotnet/aspnet:{base_tag}\n"
        "WORKDIR /app\n"
        "COPY --from=build /app ./\n"
        f'ENTRYPOINT ["dotnet", "{assembly}.dll"]\n'
    )


def render_netcore_ci(discovery: Discovery, config: StepConfig) -> str:
    """Render the .NET Core CI workflow YAML for ``discovery`` and ``config``."""
    sdk, _ = _sdk(getattr(discovery, "target_framework", None))
    do_scan = "scan" not in config.disabled_steps
    do_image = "image" not in config.disabled_steps

    # GHCR requires a lowercase repository; ${{ github.repository }} can contain
    # uppercase (the owner), so we lowercase it into $IMAGE in a step below.
    image = "${{ env.IMAGE }}"
    sha_ref = image + ":${{ github.sha }}"
    latest_ref = image + ":latest"

    steps: list[str] = [
        "      - uses: actions/checkout@v4",
        "      - name: Setup .NET",
        "        uses: actions/setup-dotnet@v4",
        f"        with:\n          dotnet-version: '{sdk}'",
        "      - name: Restore",
        "        run: dotnet restore",
    ]
    if config.enabled("build"):
        steps += [
            "      - id: build",
            "        name: Build",
            "        run: dotnet build --configuration Release --no-restore",
        ]
    if config.enabled("test"):
        steps += [
            "      - id: test",
            "        name: Run unit tests",
            '        run: dotnet test --configuration Release --no-build --logger "trx"',
        ]
    if config.enabled("sonar"):
        steps += [
            "      - id: sonar",
            "        name: SonarQube scan",
            "        env:",
            "          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}",
            "        run: |",
            "          dotnet tool install --global dotnet-sonarscanner",
            (
                '          dotnet sonarscanner begin /k:"${{ github.repository }}"'
                ' /d:sonar.host.url="${{ vars.SONAR_HOST_URL }}" /d:sonar.login="$SONAR_TOKEN"'
            ),
            "          dotnet build --configuration Release",
            '          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"',
        ]
    if do_scan:
        # Dependency/filesystem scan — substitute for Sonatype SCA. Fails on a
        # fixable CRITICAL finding (PRD CR-1).
        steps += [
            "      - id: scan",
            "        name: Trivy dependency scan (SCA)",
            f"        uses: {TRIVY_ACTION}",
            "        with:",
            "          scan-type: fs",
            "          scan-ref: .",
            "          severity: CRITICAL",
            "          ignore-unfixed: true",
            "          exit-code: '1'",
        ]
    if do_image:
        # FR-N.10: build the image, scan it (substitute for Wiz), emit a CycloneDX
        # SBOM, then publish to GHCR (the substitute for Nexus, PRD §8).
        steps += [
            "      - name: Set image name (GHCR requires a lowercase repository)",
            '        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"',
            "      - name: Log in to GHCR",
            "        uses: docker/login-action@v3",
            "        with:",
            "          registry: ghcr.io",
            "          username: ${{ github.actor }}",
            "          password: ${{ secrets.GITHUB_TOKEN }}",
            "      - id: image",
            "        name: Build image",
            "        uses: docker/build-push-action@v6",
            "        with:",
            "          context: .",
            "          load: true",
            "          tags: " + sha_ref,
            "      - id: image-scan",
            "        name: Trivy image scan",
            f"        uses: {TRIVY_ACTION}",
            "        with:",
            "          scan-type: image",
            "          image-ref: " + sha_ref,
            "          severity: CRITICAL",
            "          ignore-unfixed: true",
            "          exit-code: '0'   # report-only in the demo; set '1' to gate the push in prod",
            "      - id: sbom",
            "        name: Generate SBOM (CycloneDX)",
            f"        uses: {TRIVY_ACTION}",
            "        with:",
            "          scan-type: image",
            "          image-ref: " + sha_ref,
            "          format: cyclonedx",
            "          output: sbom.cyclonedx.json",
            "      - id: image-push",
            "        name: Push image to GHCR",
            "        run: |",
            "          docker tag " + sha_ref + " " + latest_ref,
            "          docker push " + sha_ref,
            "          docker push " + latest_ref,
        ]

    permissions = "  contents: read\n"
    if do_image:
        permissions += "  packages: write\n"  # required to push to GHCR

    steps_block = "\n".join(steps)
    return (
        "name: CI\n"
        "on: [push, workflow_dispatch]\n"  # commit trigger (FR-N.4) + manual run
        "permissions:\n"
        f"{permissions}"
        "jobs:\n"
        "  ci:\n"
        f"    runs-on: {discovery.runner}\n"
        "    steps:\n"
        f"{steps_block}\n"
    )


class NetCoreWorkflowGenerator(WorkflowGenerator):
    """Emit the .NET Core CI workflow (+ a Dockerfile when needed) as an artifact."""

    def generate(
        self,
        discovery: Discovery,
        config: StepConfig,
        feedback: list[str] | None = None,
    ) -> WorkflowArtifact:
        files = {WORKFLOW_PATH: render_netcore_ci(discovery, config)}
        # Add a Dockerfile only when image build is enabled and the repo has none.
        if "image" not in config.disabled_steps and not getattr(discovery, "has_dockerfile", False):
            files[DOCKERFILE_PATH] = render_dockerfile(discovery)
        return WorkflowArtifact(primary_path=WORKFLOW_PATH, files=files)
